version: "3.7"
services:
  carfleet_api:
    build: .
    restart: "no"
    ports:
      - "8081:8081"
    links:
      - mongo_db
    depends_on:
      - mongo_db

  mongo_db:
    image: "mongo:4.4.3"
    restart: "no"
    ports:
      - "27018:27017"